events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name support.atlas.local; # Remplace par ton vrai nom de domaine plus tard

        location / {
            # On redirige le trafic vers l'IP statique de la VM GLPI
            proxy_pass http://10.20.0.20;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}